// FXnRXn copyright notice

#pragma once

#include "NativeGameplayTags.h"

namespace KWGameplayTags
{
	//--  Input Tags  --

	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unequip_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Sword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unequip_Sword);

	//--  Player Tags  --
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	//--  Event  --
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipAxe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquipAxe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipSword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquipSword);
}
