// FXnRXn copyright notice

#pragma once

#include "NativeGameplayTags.h"

namespace KWGameplayTags
{
	//--  Input Tags  --
	//--> To handle Input Mapping context and input action
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unequip_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Sword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unequip_Sword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword);

	//--  Player Tags  --
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	//--> Ability
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);

	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword);
	

	//--  Event  --
	//--> Check which current weapon tag/weapon player have
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipAxe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquipAxe);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipSword);
	KNIGHTWARRIOR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquipSword);
}
